### ISSUE TITLE
Fix: Articles are all the same

### ISSUE THREAD

**Issue by minhnimble** [nimblehq/nimble-medium-ios#149]
## Issue

Articles data in Feeds screen are all the same.

<img src="https://user-images.githubusercontent.com/70877098/134456489-50019bac-200b-41b8-9492-8e1db09ca502.PNG" width="300">

## Expected

Articles data in Feeds screen should be reflected correctly from the API response.

## Steps to reproduce

1. Open the application.
2. Check the articles data in the Feeds screen.
3. Observe the result

**Comment by minhnimble** [comment]
This issue is still happening on staging build v1.1.0 (196). Please help take a look again 🙏

**Comment by markgravity** [comment]
@minhnimble it's their API issue, they redirect a request with params
`https://conduit.productionready.io/api/articles?limit=10&offset=10`
-> `https://conduit.productionready.io/api/articles`

You can try it on your browser 😁
