### ISSUE TITLE
Set up CI pipeline

### ISSUE THREAD

**Issue by minhnimble** [nimblehq/nimble-medium-ios#2]
## Why

When starting a new project, the CI pipeline should be setup properly for automatically asserting the new code’s correctness before developers merge code changes.

## Acceptance Criteria
- [ ] Setup CI pipeline for building, linting and running tests with a preferred platform (Bitrise, CircleCI, Github Action, etc.).
- [ ] Setup the triggers for both PR-related and push events.

**Comment by markgravity** [comment]
@minhnimble hmm I think you got wrong my mean in [this](https://github.com/nimblehq/nimble-medium-ios/pull/36#issuecomment-896463055) 
I mean that I gonna refactor the default navigation bar and this CI script is working fine as intend 😁
