### ISSUE TITLE
Setup project localization

### ISSUE THREAD

**Issue by minhnimble** [nimblehq/nimble-medium-ios#20]
## Why

When starting a new project, the project localization should be setup properly for removing the usage of hardcoded texts and thus easily supporting a new language in the future.

## Acceptance Criteria
- [ ] Setup the 3rd libraries for supporting localization.
- [ ] Setup the `.strings` keys file with English as the only language to support for now.

**Comment by markgravity** [comment]
@minhnimble  can we use `.strings`? I think it's common use in our project 🤔

**Comment by minhnimble** [comment]
> @minhnimble can we use `.strings`? I think it's common use in our project 🤔

Yes sure man, let's stick to our team convention, let me update the AC 👍
