### ISSUE TITLE
Set up CD pipeline for staging releases

### ISSUE THREAD

**Issue by minhnimble** [nimblehq/nimble-medium-ios#3]
## Why

When starting a new project, the CD pipeline should be setup properly for automatically testing to validate if changes to the codebase are correct and stable for immediate autonomous deployment to a staging environment.

## Acceptance Criteria
- [ ] Setup the CD pipeline for releasing the staging app using a preferred platform (Bitrise, CircleCI, Github Action, etc.) and release it on TestFlight or Firebase Distribution.
- [ ] Setup the triggers for every new push to develop branch.

**Comment by markgravity** [comment]
@minhnimble should we stick with [our ios-template](https://github.com/nimblehq/ios-templates/blob/develop/.github/workflows/deploy_Firebase.yml) which deploying every pushes in `develop`

**Comment by minhnimble** [comment]
@markgravity no problem for me since we should follow the team convention, let's go with that and I will update the requirement 👍
