### ISSUE TITLE
As a user, I can toggle to update my follow status of another user from the article details screen

### ISSUE THREAD

**Issue by minhnimble** [nimblehq/nimble-medium-ios#50]
## Why

When the users logged in the application successfully, they can toggle to follow or unfollow another user in the `Article Details` screen. Following a user will show all the articles of this user in the `My Feeds` tab from the `Home` screen.

## Acceptance Criteria
- [ ] Reuse the `Article Details` screen UI layout from #19.
- [ ] Create a follow button with 2 states for the follow button: `normal` and `selected` state. Default the state to `normal` for now.
- [ ] Add the follow button to be right next to author name label with text: `Follow` for `normal` state and `Unfollow` for `selected` state  as shown in the below design.

## Resources

- Sample screen UI layout with the follow button in `normal` state:

<img width="568" alt="Screen Shot 2021-08-09 at 13 15 33 copy 2" src="https://user-images.githubusercontent.com/70877098/129020782-606169e4-a9b0-460b-9d4a-1a3fdf0eefdc.png">

- Sample screen UI layout with the follow button in `selected` state:

<img width="575" alt="Screen Shot 2021-08-12 at 11 06 46 copy" src="https://user-images.githubusercontent.com/70877098/129151019-ccd5c60c-b7b5-4042-98a0-dc3c715e4602.png">

**Comment by markgravity** [comment]
@minhnimble I think we should align the `Follow` button to the right, it more mobile feel IMO, what do you think? 🤔
<img width="367" alt="Screen Shot 2021-10-11 at 14 52 44" src="https://user-images.githubusercontent.com/17875522/136752772-6184260b-a79f-4d3f-b33d-4b0dd33e8de5.png">
